language: ruby

rvm: 2.4.3

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - squashfs-tools
      - gcc-4.8
      - g++-4.8
      - texinfo

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install squashfs; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - mksquashfs -version
  - ruby --version

script:
  - ruby tests/ruby-compiler
